In [1]:
import os
import numpy as np
from numpy import copy


path_uni = '/data/PCC_Open3DML/skitti_PCC'

In [2]:
val_dict = {
    0:	0,
    1: 0,
    2: 2,
    3: 3,
    4: 4,
    5: 5,
    6: 6,
    7: 7,
    8: 8,
    9: 9,
    10: 10,
    11: 11,
    12: 12,
    13: 13,
    14: 14,
    15: 15,
    16: 16,
    17: 17,
    18: 18,
    19: 19,

    24:	1,
    104: 1,
    68: 2,
    73: 3,
    78: 4,
    112: 5,
    25: 6,
    96: 6,
    100: 7,
    75: 8,
    77: 8,
    103: 9,
    81: 10,
    76: 11,
    92: 12,
    28: 13,
    64: 13,
    82: 14,
    105: 15,
    22: 16,
    109: 16,
    23: 17,
    74: 17,
    80: 18,
    21: 19,
    110: 19
}


In [3]:
# change values based on dict
# delete any values larger than 19 - replace with 0

In [4]:
for root, dirs, files in os.walk(path_uni):
    for file in files:
        if file.endswith(".label"):
            checker = os.path.join(root, file)
            labels = np.fromfile(checker, dtype='uint32')

            newArray = copy(labels)

            (unique, counts) = np.unique(newArray, return_counts=True)
            frequencies = np.asarray((unique, counts)).T
            print(frequencies)

            for k, v in val_dict.items(): newArray[labels==k] = v

            newArray[newArray >= 20] = 0

            (uniq, count) = np.unique(newArray, return_counts=True)
            frequenci = np.asarray((uniq, count)).T
            print(frequenci)

            newArray.astype('uint32').tofile(checker)

            del labels
            del newArray
            del unique
            del counts
            del frequencies
            

[[       0 27436963]
 [       1   179954]
 [       2  2762184]
 [       3  2662699]
 [       4    65221]
 [       5     6760]
 [       6     9679]
 [       9     9092]
 [      11    45388]
 [      12    17138]
 [      13      698]
 [      14      225]
 [      15     2038]
 [      17    15693]
 [      19    78746]]
[[       0 27436963]
 [       1   179954]
 [       2  2762184]
 [       3  2662699]
 [       4    65221]
 [       5     6760]
 [       6     9679]
 [       9     9092]
 [      11    45388]
 [      12    17138]
 [      13      698]
 [      14      225]
 [      15     2038]
 [      17    15693]
 [      19    78746]]
[[     0 624810]
 [     2 212388]
 [     3  48089]
 [     5  21760]]
[[     0 624810]
 [     2 212388]
 [     3  48089]
 [     5  21760]]
[[     0 939488]
 [     2  63909]
 [     3 228132]
 [     5 155873]
 [     9   3161]
 [    11  14801]
 [    15   5667]
 [    19  26557]]
[[     0 939488]
 [     2  63909]
 [     3 228132]
 [     5 155873]
 [     9   3161]
 [    11

In [2]:
for root, dirs, files in os.walk(path_uni):
    for file in files:
        if file.endswith(".label"):
            checker = os.path.join(root, file)
            labels = np.fromfile(checker, dtype='uint32')
            labels[labels == 99] = 0
            labels[labels == 71] = 0
            labels[labels == 69] = 0
            labels[labels == 1] = 0
            labels[labels == 106] = 0
            labels.astype('uint32').tofile(checker)





            #take label file
            #open it as writable
            #go through each label
            #if label == 71, 69, 0r 99 change to 1
            #save label
